def getSymbolHex(filter):
    return getFootprintHex(filter)

def getFootprintHex(filter):
    filter = filter.upper()
    replaceList = []
    replaceList.append(["FOOTPRINT-","FZ"])
    replaceList.append(["SYMBOL-","SZ"])
   ### kicad ones    
    replaceList.append(["",""])
    replaceList.append(["kicad-kicad-footprints".upper(),"K"])
    replaceList.append(["kicad-kicad-symbols".upper(),"K"])
    ######  OOMLOUT libraries
    replaceList.append(["kicad-oomlout_OOMP_kicad".upper(),"OOMPK"])
    replaceList.append(["kicad-digikey-kicad-library".upper(),"DIGI"])
    replaceList.append(["digiekey-footprint".upper(),""])
    replaceList.append(["oomlout_OOMP_JLCC_Basic".upper(),"JLC"])
    replaceList.append(["oomlout_OOMP_modules".upper(),"OOMPM"])
    replaceList.append(["oomlout_OOMP_JLCC_Basic".upper(),"JLC"])
    replaceList.append(["oobbOutlines".upper(),"OOBB"])
    replaceList.append(["oomlout_OOMP_parts".upper(),"OOMPP"])

    
    ######  Kicad libraries
    replaceList.append(["Varistor".upper(),"V"])
    replaceList.append(["Audio_Module".upper(),"A"])
    replaceList.append(["Battery".upper(),"BAT"])
    replaceList.append(["Button_Switch_Keyboard".upper(),"B"])
    replaceList.append(["Button_Switch_SMD".upper(),"B"])
    replaceList.append(["Button_Switch_THT".upper(),"B"])
    replaceList.append(["Buzzer_Beeper".upper(),"BZ"])
    replaceList.append(["Calibration_Scale".upper(),"CS"])
    replaceList.append(["Capacitor_SMD".upper(),"C"])
    replaceList.append(["Capacitor_Tantalum_SMD".upper(),"C"])
    replaceList.append(["Capacitor_THT".upper(),"C"])
    replaceList.append(["Connector".upper(),"CN"])
    replaceList.append(["Connector_AMASS".upper(),"CN"])
    replaceList.append(["Connector_Amphenol".upper(),"CN"])
    replaceList.append(["Connector_Audio".upper(),"CNA"])
    replaceList.append(["Connector_BarrelJack".upper(),"CNBJ"])
    replaceList.append(["Connector_Card".upper(),"CN"])
    replaceList.append(["Connector_Coaxial".upper(),"CN"])
    replaceList.append(["Connector_DIN".upper(),"CDIN"])
    replaceList.append(["Connector_Dsub".upper(),"CDSUB"])
    replaceList.append(["Connector_FFC-FPC".upper(),"CFPC"])
    replaceList.append(["Connector_Harting".upper(),"CN"])
    replaceList.append(["Connector_Harwin".upper(),"CN"])
    replaceList.append(["Connector_HDMI".upper(),"CHDMI"])
    replaceList.append(["Connector_Hirose".upper(),"C"])
    replaceList.append(["Connector_IDC".upper(),"CIDC"])
    replaceList.append(["Connector_JAE".upper(),"C"])
    replaceList.append(["Connector_JST".upper(),"CJST"])
    replaceList.append(["Connector_Molex".upper(),"CMOL"])
    replaceList.append(["Connector_PCBEdge".upper(),"CN"])
    replaceList.append(["Connector_Phoenix_GMSTB".upper(),"CN"])
    replaceList.append(["Connector_Phoenix_MC".upper(),"CNPH"])
    replaceList.append(["Connector_Phoenix_MC_HighVoltage".upper(),"CNPH"])
    replaceList.append(["Connector_Phoenix_MSTB".upper(),"CNPH"])
    replaceList.append(["Connector_Pin".upper(),"CNP"])
    replaceList.append(["Connector_PinHeader_1.00mm".upper(),"CNP"])
    replaceList.append(["Connector_PinHeader_1.27mm".upper(),"CNP"])
    replaceList.append(["Connector_PinHeader_2.00mm".upper(),"CNP"])
    replaceList.append(["Connector_PinHeader_2.54mm".upper(),"CNP"])
    replaceList.append(["Connector_PinSocket_1.00mm".upper(),"CNS"])
    replaceList.append(["Connector_PinSocket_1.27mm".upper(),"CNS"])
    replaceList.append(["Connector_PinSocket_2.00mm".upper(),"CNS"])
    replaceList.append(["Connector_PinSocket_2.54mm".upper(),"CNS"])
    replaceList.append(["Connector_RJ".upper(),"CNRJ"])
    replaceList.append(["Connector_Samtec".upper(),"CN"])
    replaceList.append(["Connector_Samtec_HLE_SMD".upper(),"CN"])
    replaceList.append(["Connector_Samtec_HLE_THT".upper(),"CN"])
    replaceList.append(["Connector_SATA_SAS".upper(),"CN"])
    replaceList.append(["Connector_Stocko".upper(),"CN"])
    replaceList.append(["Connector_TE-Connectivity".upper(),"CNTE"])
    replaceList.append(["Connector_USB".upper(),"CN"])
    replaceList.append(["Connector_Wago".upper(),"CNWA"])
    replaceList.append(["Connector_Wire".upper(),"CNWI"])
    replaceList.append(["Connector_Wuerth".upper(),"CN"])
    replaceList.append(["Converter_ACDC".upper(),"CON"])
    replaceList.append(["Converter_DCDC".upper(),"CON"])
    replaceList.append(["Crystal".upper(),"X"])
    replaceList.append(["Diode_SMD".upper(),"D"])
    replaceList.append(["Diode_THT".upper(),"D"])
    replaceList.append(["Display".upper(),"DI"])
    replaceList.append(["Display_7Segment".upper(),"DI"])
    replaceList.append(["Ferrite_THT".upper(),"F"])
    replaceList.append(["Fiducial".upper(),"FID"])
    replaceList.append(["Filter".upper(),"FIL"])
    replaceList.append(["Fuse".upper(),"FU"])
    replaceList.append(["Heatsink".upper(),"H"])
    replaceList.append(["Inductor_SMD".upper(),"IN"])
    replaceList.append(["Inductor_THT".upper(),"IN"])
    replaceList.append(["Jumper".upper(),"J"])
    replaceList.append(["LED_SMD".upper(),"L"])
    replaceList.append(["LED_THT".upper(),"L"])
    replaceList.append(["Module".upper(),"MO"])
    replaceList.append(["Mounting_Wuerth".upper(),"MON"])
    replaceList.append(["MountingEquipment".upper(),"MON"])
    replaceList.append(["MountingHole".upper(),"HOL"])
    replaceList.append(["NetTie".upper(),"NT"])
    replaceList.append(["Obsolete".upper(),"OB"])
    replaceList.append(["OptoDevice".upper(),"OP"])
    replaceList.append(["Oscillator".upper(),"OCS"])
    replaceList.append(["Package_BGA".upper(),"BGA"])
    replaceList.append(["Package_CSP".upper(),"CSP"])
    replaceList.append(["Package_DFN_QFN".upper(),"DFN"])
    replaceList.append(["Package_DIP".upper(),"DIP"])
    replaceList.append(["Package_DirectFET".upper(),"DFET"])
    replaceList.append(["Package_LCC".upper(),"LCC"])
    replaceList.append(["Package_LGA".upper(),"LGA"])
    replaceList.append(["Package_QFP".upper(),"QFP"])
    replaceList.append(["Package_SIP".upper(),"SIP"])
    replaceList.append(["Package_SO".upper(),"SO"])
    replaceList.append(["Package_SO_J-Lead".upper(),"SO"])
    replaceList.append(["Package_SON".upper(),"SON"])
    replaceList.append(["Package_TO_SOT_SMD".upper(),"SOT"])
    replaceList.append(["Package_TO_SOT_THT".upper(),"SOT"])
    replaceList.append(["Potentiometer_SMD".upper(),"P"])
    replaceList.append(["Potentiometer_THT".upper(),"P"])
    replaceList.append(["Relay_SMD".upper(),"REL"])
    replaceList.append(["Relay_THT".upper(),"REL"])
    replaceList.append(["Resistor_SMD".upper(),"R"])
    replaceList.append(["Resistor_THT".upper(),"R"])
    replaceList.append(["RF".upper(),"RF"])
    replaceList.append(["RF_Antenna".upper(),"RF"])
    replaceList.append(["RF_Converter".upper(),"RF"])
    replaceList.append(["RF_GPS".upper(),"GPS"])
    replaceList.append(["RF_GSM".upper(),"GSM"])
    replaceList.append(["RF_Mini-Circuits".upper(),"RF"])
    replaceList.append(["RF_Module".upper(),"RF"])
    replaceList.append(["RF_Shielding".upper(),"RFS"])
    replaceList.append(["RF_WiFi".upper(),"RF"])
    replaceList.append(["Rotary_Encoder".upper(),"RE"])
    replaceList.append(["Sensor".upper(),"SEN"])
    replaceList.append(["Sensor_Audio".upper(),"SA"])
    replaceList.append(["Sensor_Current".upper(),"SCU"])
    replaceList.append(["Sensor_Distance".upper(),"SDI"])
    replaceList.append(["Sensor_Humidity".upper(),"SHU"])
    replaceList.append(["Sensor_Motion".upper(),"SMO"])
    replaceList.append(["Sensor_Pressure".upper(),"SPR"])
    replaceList.append(["Sensor_Voltage".upper(),"SV"])
    replaceList.append(["Socket".upper(),"SO"])
    replaceList.append(["Symbol".upper(),"SY"])
    replaceList.append(["TerminalBlock".upper(),"TB"])
    replaceList.append(["TerminalBlock_4Ucon".upper(),"TB4U"])
    replaceList.append(["TerminalBlock_Altech".upper(),"TBAL"])
    replaceList.append(["TerminalBlock_Dinkle".upper(),"TBDN"])
    replaceList.append(["TerminalBlock_MetzConnect".upper(),"TBME"])
    replaceList.append(["TerminalBlock_Philmore".upper(),"TBPM"])
    replaceList.append(["TerminalBlock_Phoenix".upper(),"TBPH"])
    replaceList.append(["TerminalBlock_RND".upper(),"TBRN"])
    replaceList.append(["TerminalBlock_TE-Connectivity".upper(),"TBTE"])
    replaceList.append(["TerminalBlock_WAGO".upper(),"TBWA"])
    replaceList.append(["TerminalBlock_Wuerth".upper(),"TBWU"])
    replaceList.append(["TestPoint".upper(),"TP"])
    replaceList.append(["Transformer_SMD".upper(),"TR"])
    replaceList.append(["Transformer_THT".upper(),"TR"])
    replaceList.append(["Transistor_Power_Module".upper(),"Q"])
    replaceList.append(["Valve".upper(),"VA"])
    
    #kicad extras
    replaceList.append(["Metric".upper(),"VA"])

    ### adafruit ones
    ######  Library
    replaceList.append(["",""])
    replaceList.append(["eagle-Adafruit-Eagle-Library-adafruit-".upper(),"A"])
    ######  additions
    replaceList.append(["",""])
    replaceList.append(["-0.7MM","07"])
    replaceList.append(["-0.5MM","05"])
    replaceList.append(["-3.5MM","35"])
    replaceList.append(["ADAFRUIT","ADA"])
    replaceList.append(["ARDUINO","ARD"])
    replaceList.append(["-BIG","B"])
    replaceList.append(["CLUEFRUIT","BF"])
    replaceList.append(["-BIGPOGO","BP"])
    replaceList.append(["-CLEANBIG","CB"])
    replaceList.append(["-CLEAN","C"])
    replaceList.append(["-CB","CB"])
    replaceList.append(["_DIM","D"])
    replaceList.append(["-DIM","D"])
    replaceList.append(["EDGELAUNCH","EL"])
    replaceList.append(["FEATHERWING","FW"])
    
    replaceList.append(["INLINE","I"])
    replaceList.append(["JACK","J"])
    replaceList.append(["EAGLEBONE","EB"])
    replaceList.append(["MINI_MELF","MM"])
    replaceList.append(["MOLEX","MX"])
    
    replaceList.append(["NARROW","N"])
    replaceList.append(["NOIOREF","NI"])
    replaceList.append(["-NOTEXT","NT"])
    replaceList.append(["-NODIM","ND"])
    replaceList.append(["-NOHOLE","NH"])
    replaceList.append(["-OSHWLOGO","OL"])
    replaceList.append(["-PANASONIC","P"])
    replaceList.append(["PUSHBUTTON","PB"])
    
    replaceList.append(["PWRONLY",""])
    replaceList.append(["PTH","P"])
    
    replaceList.append(["REVERSE","R"])
    replaceList.append(["-ROUND","R"])    
    replaceList.append(["SEGMENT","S"])
    replaceList.append(["-SIDE","SD"])
    replaceList.append(["SKINNYPADS","SP"])
    replaceList.append(["SMA","S"])
    replaceList.append(["SMD","SM"])
    replaceList.append(["SKINNIER","SK"])
    replaceList.append(["-SMALLS","S"])
    replaceList.append(["-SMT","S"])
    replaceList.append(["_SMT","S"])
    
    replaceList.append(["THM","T"])
    replaceList.append(["-LOCK","L"])
    
    replaceList.append(["WHEEL","W"])
    
    ### Dangerous Prototypes ones
    ######  Library
    replaceList.append(["",""])
    replaceList.append(["DangerousPrototypes-Eagle-Library-dp_devices.v6-".upper(),"DP"])
   ### eagle ones    
    replaceList.append(["",""])
    replaceList.append(["eagle-eagle-default-".upper(),"E"])


   
    
    ### pimoroni ones    
    replaceList.append(["",""])
    replaceList.append(["eagle-Pimoroni-Eagle-Library".upper(),"P"])

    ##libraries
    replaceList.append(["",""])
    replaceList.append(["-gee_s".upper(),"G"])
    replaceList.append(["-pimoroni".upper(),""])
    replaceList.append(["-pimoroni-boards".upper(),"B"])
    replaceList.append(["-pimoroni-connectors".upper(),"C"])
    replaceList.append(["-pimoroni-flotilla".upper(),"FL"])
    replaceList.append(["-pimoroni-fpc".upper(),"F"])
    replaceList.append(["-pimoroni-headers".upper(),"H"])
    replaceList.append(["-pimoroni-holes".upper(),"HO"])
    replaceList.append(["-pimoroni-ics".upper(),"I"])
    replaceList.append(["-pimoroni-mechanical".upper(),"M"])
    replaceList.append(["-pimoroni-misc".upper(),"MI"])
    replaceList.append(["-pimoroni-optoelectronics".upper(),"O"])
    replaceList.append(["-pimoroni-passives".upper(),"P"])
    replaceList.append(["-pimoroni-rc".upper(),"RC"])


    ### sparkfun ones
    replaceList.append(["eagle-SparkFun-Eagle-Libraries-".upper(),"S"])
    replaceList.append(["LilyPad-Wearables-".upper(),"LW"])
    replaceList.append(["SparkFun-Aesthetics-".upper(),"A"])
    replaceList.append(["SparkFun-Batteries-".upper(),"B"])
    replaceList.append(["SparkFun-Boards-".upper(),"BO"])
    replaceList.append(["SparkFun-Buzzard-".upper(),"BU"])
    replaceList.append(["SparkFun-Capacitors-".upper(),"C"])
    replaceList.append(["SparkFun-Clocks-".upper(),"CL"])
    replaceList.append(["SparkFun-Coils-".upper(),"CO"])
    replaceList.append(["Sparkfun-Connectors-".upper(),"CN"])
    replaceList.append(["SparkFun-DiscreteSemi-".upper(),"DS"])
    replaceList.append(["SparkFun-Displays-".upper(),"D"])
    replaceList.append(["SparkFun-Electromechanical-".upper(),"E"])
    replaceList.append(["SparkFun-Fuses-".upper(),"F"])
    replaceList.append(["SparkFun-GPS-".upper(),"G"])
    replaceList.append(["SparkFun-Hardware-".upper(),"H"])
    replaceList.append(["SparkFun-IC-Amplifiers-".upper(),"IA"])
    replaceList.append(["SparkFun-IC-Comms-".upper(),"IC"])
    replaceList.append(["SparkFun-IC-Conversion-".upper(),"IV"])
    replaceList.append(["SparkFun-IC-Logic-".upper(),"IL"])
    replaceList.append(["SparkFun-IC-Memory-".upper(),"IM"])
    replaceList.append(["SparkFun-IC-Microcontroller-".upper(),"IU"])
    replaceList.append(["SparkFun-IC-Power-".upper(),"IP"])
    replaceList.append(["SparkFun-IC-Special-Function-".upper(),"IS"])
    replaceList.append(["SparkFun-Jumpers-".upper(),"J"])
    replaceList.append(["SparkFun-LED-".upper(),"L"])
    replaceList.append(["SparkFun-MicroMod-".upper(),"M"])
    replaceList.append(["SparkFun-PowerSymbols-".upper(),"P"])
    replaceList.append(["SparkFun-Resistors-".upper(),"R"])
    replaceList.append(["SparkFun-Retired-".upper(),"RT"])
    replaceList.append(["SparkFun-RF-".upper(),"RF"])
    replaceList.append(["SparkFun-Sensors-".upper(),"S"])
    replaceList.append(["SparkFun-Switches-".upper(),"W"])
    replaceList.append(["User-Submitted-".upper(),"U"])

    ###### sparkfun resistors
    replaceList.append(["",""])
    replaceList.append(["_MURATA","M"])
    
    replaceList.append(["_NO0-CREAM","NC"])
    replaceList.append(["_NO_CREAM","NC"])
    replaceList.append(["-TIGHT","T"])
    replaceList.append(["_RA","RA"])
    replaceList.append(["-KIT","K"])
    replaceList.append(["_KIT","K"])
    replaceList.append(["LONGPADS","L"])
    replaceList.append(["LOCK","L"])
    replaceList.append(["STRAIGHT","S"])
    replaceList.append(["HOLES","H"])
    
    
    
    
    replaceList.append(["AXIAL-","A"])
    
    replaceList.append(["RESONATOR","R"])
    
    replaceList.append(["TRIMPOT-SMD","TS"])

    replaceList.append(["FLAME","F"])
    replaceList.append(["-SHROUDEDS","SH"])
    replaceList.append(["-SHROUDED","SH"])
    replaceList.append(["-QWIIC","Q"])
    

    ### common ones
    replaceList.append(["",""])
    replaceList.append(["0204","24"])
    replaceList.append(["0207","27"])
    replaceList.append(["0204","24"])
    replaceList.append(["0402","42"])
    replaceList.append(["0603","63"])
    ###### Last ditch
    #####Sizes
    replaceList.append(["LARGE","L"])
    replaceList.append(["SMALL","S"])
    
    replaceList.append(["",""])
    replaceList.append(["BATTCON","BC"])
    replaceList.append(["BUTTON","B"])
    replaceList.append(["COPPER","C"])
    replaceList.append(["FIDUCIAL","F"])
    replaceList.append(["LED","L"])
    replaceList.append(["LOGO","L"])
    replaceList.append(["MICRO","M"])
    replaceList.append(["NAME","N"])
    replaceList.append(["POGOPIN","PP"])
    
    replaceList.append(["RADIAL","R"])    
    replaceList.append(["SHIELD","SH"])    
    replaceList.append(["TRANSFORMER","TR"])
    
    replaceList.append(["RECTANGULAR","R"])
    replaceList.append(["MM",""])

    replaceList.append(["SOP","S"])

    replaceList.append(["MIL","M"])
    replaceList.append(["USB","U"])    
    replaceList.append(["MINI","M"])

    replaceList.append(["/",""])
    replaceList.append(["-",""])
    replaceList.append(["_",""])
    replaceList.append(["0",""])
    replaceList.append([":",""])
    replaceList.append([".",""])
    replaceList.append([",",""])
    ###### MM
    for x in range(9):
        xs = str(x)
        replaceList.append(["-0" + xs + "MM",xs])
        replaceList.append(["-0" + xs + "mm",xs])
        replaceList.append(["-" + xs + "MM",xs])
        replaceList.append(["-" + xs + "mm",xs])
        replaceList.append([xs + "MM",xs])
        replaceList.append([xs + "MM",xs])

    ##Common words
    replaceList.append(["FEMALE","F"])
    replaceList.append(["HORIZONTAL","H"])
    replaceList.append(["VERTICAL","F"])
    replaceList.append(["EDGEPIN","EP"])
    replaceList.append(["OFFSET","O"])
    replaceList.append(["HOUSED","H"])
    replaceList.append(["MOUNTINGHOLES","MH"])
    replaceList.append(["MOUNTHOLE","MH"])
    replaceList.append(["SWITCH","SW"])
    replaceList.append(["TACTILE","T"])
    replaceList.append(["THREADED","TH"])
    replaceList.append(["FLANGE","F"])
    replaceList.append(["OOMLOUT","OOM"])
    replaceList.append(["OOMLOUT","OOM"])
    replaceList.append(["POTENTIOMETER","POT"])
    replaceList.append(["PhoenixContact_MCV_1".upper(),"MCV"])
    replaceList.append(["PHEONIX".upper(),"PX"])
    replaceList.append(["CONTACT".upper(),"CT"])
    replaceList.append(["WIRE".upper(),"W"])
    replaceList.append(["PAD".upper(),"P"])
    replaceList.append(["PACKAGE".upper(),"P"])
    replaceList.append(["LONG".upper(),"L"])
    replaceList.append(["NICHICON".upper(),"NC"])
    replaceList.append(["INDUCTOR".upper(),"IN"])
    replaceList.append(["SQUARE".upper(),"SQ"])
    replaceList.append(["PANASONIC".upper(),"PAN"])
    replaceList.append(["SANTANA".upper(),"SAN"])
    replaceList.append(["SPRING".upper(),"SP"])
    replaceList.append(["TERMINAL".upper(),"T"])
    replaceList.append(["SKINNIER".upper(),"SK"])
    replaceList.append(["PETAL".upper(),"P"])
    replaceList.append(["HOLE".upper(),"H"])
    replaceList.append(["LONG".upper(),"L"])
    replaceList.append(["MEDIUM".upper(),"M"])
    replaceList.append(["GESTURE".upper(),"G"])
    replaceList.append(["SENSE".upper(),"S"])
    replaceList.append(["TEXT".upper(),"T"])
    replaceList.append(["ORDERING".upper(),"O"])
    replaceList.append(["PRODUCTION".upper(),"P"])
    replaceList.append(["INSTRUCTIONS".upper(),"IN"])
    replaceList.append(["ASPECT".upper(),"A"])
    replaceList.append(["NEGATIVE".upper(),"N"])
    replaceList.append(["INTERNAL".upper(),"IN"])
    replaceList.append(["RASPBERRY".upper(),"R"])
    replaceList.append(["RASP".upper(),"R"])
    replaceList.append(["PROCESSOR".upper(),"P"])
    replaceList.append(["GENERIC".upper(),"G"])
    replaceList.append(["MOUNTING".upper(),"M"])
    replaceList.append(["CONNECTOR".upper(),"C"])
    replaceList.append(["CONN".upper(),"C"])
    replaceList.append(["ROW".upper(),"R"])
    replaceList.append(["LETTER".upper(),"L"])
    replaceList.append(["FIRST".upper(),"F"])
    replaceList.append(["PIN".upper(),"P"])
    replaceList.append(["COUNTERCLWISE".upper(),"CCW"])
    replaceList.append(["MOUNT".upper(),"M"])
    replaceList.append(["HARTING".upper(),"HARTING"])
    replaceList.append(["CONNECT".upper(),"C"])
    replaceList.append(["TYPE".upper(),"T"])
    replaceList.append(["HARFLEXICON".upper(),"HFLX"])
    replaceList.append(["BOTTOM".upper(),"B"])
    replaceList.append(["PROFILE".upper(),"P"])
    replaceList.append(["HOLDER".upper(),"H"])
    replaceList.append(["CLIP".upper(),"CL"])
    replaceList.append(["PCBEDGE".upper(),"PE"])
    
    replaceList.append(["POLARIZED".upper(),"PZ"])
    replaceList.append(["TOROID".upper(),"T"])
    replaceList.append(["SLIDE".upper(),"SL"])
    replaceList.append(["KING".upper(),"K"])
    replaceList.append(["HEADER".upper(),"H"])
    replaceList.append(["RIGHT".upper(),"R"])
    replaceList.append(["LEFT".upper(),"L"])
    replaceList.append(["FUSE".upper(),"F"])
    replaceList.append(["PULL".upper(),"P"])
    replaceList.append(["BACK".upper(),"B"])
    replaceList.append(["HAND".upper(),"H"])
    replaceList.append(["SOLDERING".upper(),"S"])
    replaceList.append(["THERMAL".upper(),"TH"])
    replaceList.append(["VIAS".upper(),"V"])
    replaceList.append(["SCREW".upper(),"SC"])
    replaceList.append(["DIP".upper(),"D"])


    #replaceList.append(["".upper(),""])

    for replace in replaceList:
        filter = filter.replace(replace[0],replace[1])
    return filter