
###### THIS FILE IS GENERATED BY OOMP_projects_BASE.py
import OOMP_projects_BASE

def createProjects():
    projects = []    
    
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '2D_Barcode_Scanner_Breakout', 'name': '2D Barcode Scanner Breakout', 'file': '/Hardware/2DBarcodeScanner', 'count': '18088'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '32U4_Breakout_Board', 'name': '32U4 Breakout Board', 'file': '/Hardware/32U4_Breakout', 'count': '11117'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '3D_Models', 'name': '3D Models', 'file': '/products/11231/eagle_files/PowerCell-v13', 'count': ''})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '5-Way_Tactile_Switch_Breakout', 'name': '5 Way Tactile Switch Breakout', 'file': '/Hardware/SparkFun_5-Way_Tactile_Switch_Breakout', 'count': '11187'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '74HC4051_8-Channel_Mux_Breakout', 'name': '74HC4051 8 Channel Mux Breakout', 'file': '/Hardware/SparkFun-74HC4051-8-Channel-Mux-Breakout', 'count': '13906'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '8_channel_level_shifter_TXS0108E', 'name': '8 channel level shifter TXS0108E', 'file': '/Hardware/TXS0108 Breakout', 'count': '19626'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '9DOF_Razor_IMU', 'name': '9DOF Razor IMU', 'file': '/Hardware/sparkfun-9dof-razor-imu', 'count': '14001'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': '9DOF_Sensor_Stick', 'name': '9DOF Sensor Stick', 'file': '/Hardware/SparkFun_9DoF_Sensor_Stick', 'count': '13944'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'AD5330_Breakout', 'name': 'AD5330 Breakout', 'file': '/Hardware/SparkFun_AD5330_Breakout', 'count': '12082'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'AD8232_Heart_Rate_Monitor', 'name': 'AD8232 Heart Rate Monitor', 'file': '/Hardware/AD8232_Heart_Rate_Monitor', 'count': '12650'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'Adapter_Board-ICD_ICD2', 'name': 'Adapter Board ICD ICD2', 'file': '/Hardware/SparkFun_ICD-ICD2', 'count': '193'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'Adjustable_Lipo_Charger', 'name': 'Adjustable Lipo Charger', 'file': '/Hardware/Sparkfun_Adjustable_LiPo_Charger', 'count': '14380'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL335_Breakout', 'name': 'ADXL335 Breakout', 'file': '/Hardware/ADXL335_Breakout', 'count': '9269'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL337_Breakout', 'name': 'ADXL337 Breakout', 'file': '/hardware/ADXL337 Breakout', 'count': '12786'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL345_Breakout', 'name': 'ADXL345 Breakout', 'file': '/Hardware/ADXL345_Breakout', 'count': '9836'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL345_Eval', 'name': 'ADXL345 Eval', 'file': '/hardware/ADXL345_Eval_Board-v11', 'count': '9814'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL362_Breakout', 'name': 'ADXL362 Breakout', 'file': '/Hardware/ADXL362_BOB', 'count': '11446'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'ADXL377_Breakout', 'name': 'ADXL377 Breakout', 'file': '/hardware/ADXL377 Breakout', 'count': '12803'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'AD_Stereo_Converter-PCM1803A', 'name': 'AD Stereo Converter PCM1803A', 'file': '/Hardware/PCM1803A_Breakout-v11', 'count': '9365'})
    projects.append({'oompType': 'PROJ', 'oompSize': 'SPAR', 'format': 'eagle', 'github': 'https://github.com/sparkfun/', 'repo': 'Alphabet_Boards', 'name': 'Alphabet Boards', 'file': '/Hardware/Alphabet_Boards', 'count': ''})
