

def load(td):
    td.append({'category' : 'type', 'code' : 'ANTE', 'name' : 'Antenna'})
    td.append({'category' : 'type', 'code' : 'BAHO', 'name' : 'Battery Holder'})
    td.append({'category' : 'type', 'code' : 'BAPI', 'name' : 'Badge Pin'})
    td.append({'category' : 'type', 'code' : 'BREB', 'name' : 'Breadboard'})
    td.append({'category' : 'type', 'code' : 'BUTA', 'name' : 'Pushbutton (Tactile)'})
    td.append({'category' : 'type', 'code' : 'BUTP', 'name' : 'Pushbutton'})
    td.append({'category' : 'type', 'code' : 'BUZZ', 'name' : 'Buzzer'})
    td.append({'category' : 'type', 'code' : 'CABL', 'name' : 'Cable'})
    td.append({'category' : 'type', 'code' : 'CAPC', 'name' : 'Capacitor (Ceramic)'})
    td.append({'category' : 'type', 'code' : 'CAPE', 'name' : 'Capacitor (Electrolytic)'})
    td.append({'category' : 'type', 'code' : 'CAPT', 'name' : 'Capacitor (Tantalum)'})
    td.append({'category' : 'type', 'code' : 'CERE', 'name' : 'Ceramic Resonator'})
    td.append({'category' : 'type', 'code' : 'DBCO', 'name' : 'Connector'})
    td.append({'category' : 'type', 'code' : 'CRHO', 'name' : 'Crimp Housing'})
    td.append({'category' : 'type', 'code' : 'DCJP', 'name' : 'DC Jack'})
    td.append({'category' : 'type', 'code' : 'DCPP', 'name' : 'DC Plug'})
    td.append({'category' : 'type', 'code' : 'DIOD', 'name' : 'Diode'})
    td.append({'category' : 'type', 'code' : 'DIOS', 'name' : 'Diode (Schottky)'})
    td.append({'category' : 'type', 'code' : 'DISP', 'name' : 'Display'})
    td.append({'category' : 'type', 'code' : 'FERB', 'name' : 'Ferrite Bead'})
    td.append({'category' : 'type', 'code' : 'HEAD', 'name' : 'Header'})
    td.append({'category' : 'type', 'code' : 'HEAS', 'name' : 'Header (Socket)'})
    td.append({'category' : 'type', 'code' : 'HEAL', 'name' : 'Header (Long)'})
    td.append({'category' : 'type', 'code' : 'HEDS', 'name' : 'Headphone Socket'})
    td.append({'category' : 'type', 'code' : 'HELF', 'name' : 'Female Header (Long)'})
    td.append({'category' : 'type', 'code' : 'HESH', 'name' : 'Heat Shrink'})
    td.append({'category' : 'type', 'code' : 'ICIC', 'name' : ''})
    td.append({'category' : 'type', 'code' : 'MCUU', 'name' : 'MCU'})
    td.append({'category' : 'type', 'code' : 'ICSO', 'name' : 'IC Socket'})
    td.append({'category' : 'type', 'code' : 'INDU', 'name' : 'Inductor'})
    td.append({'category' : 'type', 'code' : 'JSTS', 'name' : 'JST Socket'})
    td.append({'category' : 'type', 'code' : 'JUMP', 'name' : 'Jumper'})
    td.append({'category' : 'type', 'code' : 'LEDS', 'name' : 'LED'})
    td.append({'category' : 'type', 'code' : 'MICR', 'name' : 'Microphone'})
    td.append({'category' : 'type', 'code' : 'MOSN', 'name' : 'N-Ch. MOSFET'})
    td.append({'category' : 'type', 'code' : 'MOSP', 'name' : 'P-Ch. MOSFET'})
    td.append({'category' : 'type', 'code' : 'MOTO', 'name' : 'Motor'})
    td.append({'category' : 'type', 'code' : 'MOTV', 'name' : 'Motor (Vibrating)'})
    td.append({'category' : 'type', 'code' : 'NHFF', 'name' : 'Nylon Standoff (F-F)'})
    td.append({'category' : 'type', 'code' : 'NNUT', 'name' : 'Nylon Nut'})
    td.append({'category' : 'type', 'code' : 'NSCR', 'name' : 'Nylon Screw'})
    td.append({'category' : 'type', 'code' : 'NUTT', 'name' : 'Nut'})
    td.append({'category' : 'type', 'code' : 'OPAM', 'name' : 'Op Amp'})
    td.append({'category' : 'type', 'code' : 'PHTR', 'name' : 'Phototransistor'})
    td.append({'category' : 'type', 'code' : 'POTE', 'name' : 'Potentiometer'})
    td.append({'category' : 'type', 'code' : 'PIEZ', 'name' : 'Piezo Element'})
    td.append({'category' : 'type', 'code' : 'POAD', 'name' : 'Power Adapter'})
    td.append({'category' : 'type', 'code' : 'PRIV', 'name' : 'Plastic Rivet'})
    td.append({'category' : 'type', 'code' : 'RBCC', 'name' : 'Crimped Ribbon Cable'})
    td.append({'category' : 'type', 'code' : 'REFU', 'name' : 'Resetable Fuse'})
    td.append({'category' : 'type', 'code' : 'RELA', 'name' : 'Relay'})
    td.append({'category' : 'type', 'code' : 'RESA', 'name' : 'Resistor Array'})
    td.append({'category' : 'type', 'code' : 'RESE', 'name' : 'Resistor'})
    td.append({'category' : 'type', 'code' : 'RJ45', 'name' : 'RJ45'})
    td.append({'category' : 'type', 'code' : 'SCRE', 'name' : 'Machine Screw'})
    td.append({'category' : 'type', 'code' : 'SDCS', 'name' : 'SD Card Socket'})
    td.append({'category' : 'type', 'code' : 'SENS', 'name' : 'Sensor'})
    td.append({'category' : 'type', 'code' : 'SERV', 'name' : 'Servo'})
    td.append({'category' : 'type', 'code' : 'SWIS', 'name' : 'Switch (Slide)'})
    td.append({'category' : 'type', 'code' : 'TERS', 'name' : 'Screw Terminal'})
    td.append({'category' : 'type', 'code' : 'THER', 'name' : 'Thermistor'})
    td.append({'category' : 'type', 'code' : 'TILS', 'name' : 'Tilt Switch'})
    td.append({'category' : 'type', 'code' : 'TINB', 'name' : 'Tin Box'})
    td.append({'category' : 'type', 'code' : 'TRNN', 'name' : 'NPN Transistor'})
    td.append({'category' : 'type', 'code' : 'TRNP', 'name' : 'PNP Transistor'})
    td.append({'category' : 'type', 'code' : 'USBS', 'name' : 'USB Socket'})
    td.append({'category' : 'type', 'code' : 'UFLS', 'name' : 'UFL Socket'})
    td.append({'category' : 'type', 'code' : 'VARI', 'name' : 'Varistor'})
    td.append({'category' : 'type', 'code' : 'VREG', 'name' : 'Voltage Regulator'})
    td.append({'category' : 'type', 'code' : 'WIRS', 'name' : 'Stranded Wire'})
    td.append({'category' : 'type', 'code' : 'XTAL', 'name' : 'Crystal'})
    td.append({'category' : 'size', 'code' : '0402', 'name' : 'SMD (0402)'})
    td.append({'category' : 'size', 'code' : '0603', 'name' : 'SMD (0603)'})
    td.append({'category' : 'size', 'code' : '06038', 'name' : 'SMD (0603-8)'})
    td.append({'category' : 'size', 'code' : '0805', 'name' : 'SMD (0805)'})
    td.append({'category' : 'size', 'code' : '0806', 'name' : 'SMD (0806)'})
    td.append({'category' : 'size', 'code' : '1206', 'name' : 'SMD (1206)'})
    td.append({'category' : 'size', 'code' : '1263', 'name' : 'SMD (1206-3)'})
    td.append({'category' : 'size', 'code' : '1210', 'name' : 'SMD (1210)'})
    td.append({'category' : 'size', 'code' : '1812', 'name' : 'SMD (1812)'})
    td.append({'category' : 'size', 'code' : '12068', 'name' : 'SMD (1206-8)'})
    td.append({'category' : 'size', 'code' : '2312', 'name' : 'SMD (2312)'})
    td.append({'category' : 'size', 'code' : '2917', 'name' : 'SMD (2917)'})
    td.append({'category' : 'size', 'code' : 'D214', 'name' : 'SMD (DO-214)'})
    td.append({'category' : 'size', 'code' : 'MMA', 'name' : 'SMD (Mini MELF)'})
    td.append({'category' : 'size', 'code' : '3025', 'name' : 'SMD (3025)'})
    td.append({'category' : 'size', 'code' : '1515', 'name' : 'SMD (1515)'})
    td.append({'category' : 'size', 'code' : '2020', 'name' : 'SMD (2020)'})
    td.append({'category' : 'size', 'code' : '2121', 'name' : 'SMD (2121)'})
    td.append({'category' : 'size', 'code' : '3215', 'name' : 'SMD (3215)'})
    td.append({'category' : 'size', 'code' : '3216', 'name' : 'SMD (3216)'})
    td.append({'category' : 'size', 'code' : '3528', 'name' : 'SMD (3528)'})
    td.append({'category' : 'size', 'code' : '3535', 'name' : 'SMD (3535)'})
    td.append({'category' : 'size', 'code' : '3643', 'name' : 'SMD (3643)'})
    td.append({'category' : 'size', 'code' : '4628', 'name' : 'SMD (4628)'})
    td.append({'category' : 'size', 'code' : '4632', 'name' : 'SMD (4632)'})
    td.append({'category' : 'size', 'code' : '4735', 'name' : 'SMD (4735)'})
    td.append({'category' : 'size', 'code' : '5032', 'name' : 'SMD (5032)'})
    td.append({'category' : 'size', 'code' : '5050', 'name' : 'SMD (5050)'})
    td.append({'category' : 'size', 'code' : '5252', 'name' : 'SMD (5252)'})
    td.append({'category' : 'size', 'code' : '6032', 'name' : 'SMD (6032)'})
    td.append({'category' : 'size', 'code' : '6060', 'name' : 'SMD (6060)'})
    td.append({'category' : 'size', 'code' : '6727', 'name' : 'SMD (6727)'})
    td.append({'category' : 'size', 'code' : '7135', 'name' : 'SMD (7135)'})
    td.append({'category' : 'size', 'code' : '7343', 'name' : 'SMD (7343)'})
    td.append({'category' : 'size', 'code' : '7827', 'name' : 'SMD (7827)'})
    td.append({'category' : 'size', 'code' : 'AVA', 'name' : 'SMD (AVX-A)'})
    td.append({'category' : 'size', 'code' : 'AVB', 'name' : 'SMD (AVX-B)'})
    td.append({'category' : 'size', 'code' : 'AVC', 'name' : 'SMD (AVX-C)'})
    td.append({'category' : 'size', 'code' : 'S123', 'name' : 'SMD (SOD-123)'})
    td.append({'category' : 'size', 'code' : 'S323', 'name' : 'SMD (SOD-323)'})
    td.append({'category' : 'size', 'code' : 'SO123', 'name' : 'SMD (SOT-123)'})
    td.append({'category' : 'size', 'code' : 'SO223', 'name' : 'SMD (SOT-223)'})
    td.append({'category' : 'size', 'code' : 'SO323', 'name' : 'SMD (SOT-323)'})
    td.append({'category' : 'size', 'code' : 'SO363', 'name' : 'SMD (SOT-363)'})
    td.append({'category' : 'size', 'code' : 'SO23', 'name' : 'SMD (SOT-23)'})
    td.append({'category' : 'size', 'code' : 'SO23F', 'name' : 'SMD (SOT-23F)'})
    td.append({'category' : 'size', 'code' : 'SC8', 'name' : '8 Pin SMD (SOIC)'})
    td.append({'category' : 'size', 'code' : 'SC14', 'name' : '14 Pin SMD (SOIC)'})
    td.append({'category' : 'size', 'code' : 'SC16', 'name' : '16 Pin SMD (SOIC)'})
    td.append({'category' : 'size', 'code' : 'SC16W', 'name' : '16 Pin SMD (SOIC Wide)'})
    td.append({'category' : 'size', 'code' : 'SC75', 'name' : '5 Pin SMD (SC70)'})
    td.append({'category' : 'size', 'code' : 'PS20', 'name' : 'SMD (Power SO-20)'})
    td.append({'category' : 'size', 'code' : 'DFN8', 'name' : 'SMD (DFN-8)'})
    td.append({'category' : 'size', 'code' : 'DFN10', 'name' : 'SMD (DFN-10)'})
    td.append({'category' : 'size', 'code' : 'UDF6', 'name' : 'SMD (UDFN-6)'})
    td.append({'category' : 'size', 'code' : 'SO235', 'name' : 'SMD (SOT-23-5)'})
    td.append({'category' : 'size', 'code' : 'SO236', 'name' : 'SMD (SOT-23-6)'})
    td.append({'category' : 'size', 'code' : 'SO238', 'name' : 'SMD (SOT-23-8)'})
    td.append({'category' : 'size', 'code' : 'SO89', 'name' : 'SMD (SOT-89)'})
    td.append({'category' : 'size', 'code' : 'T92', 'name' : 'TO-92'})
    td.append({'category' : 'size', 'code' : 'T220', 'name' : 'TO-220'})
    td.append({'category' : 'size', 'code' : 'T252', 'name' : 'TO-252'})
    td.append({'category' : 'size', 'code' : 'G28', 'name' : '28 AWG'})
    td.append({'category' : 'size', 'code' : 'P400', 'name' : '400 Point'})
    td.append({'category' : 'size', 'code' : 'P170', 'name' : '170 Point'})
    td.append({'category' : 'size', 'code' : 'CR1220', 'name' : 'CR1220'})
    td.append({'category' : 'size', 'code' : 'P830', 'name' : '830 Point'})
    td.append({'category' : 'size', 'code' : 'W04', 'name' : '1/4 Watt'})
    td.append({'category' : 'size', 'code' : 'W08', 'name' : '1/8 Watt'})
    td.append({'category' : 'size', 'code' : 'W1', 'name' : '1 Watt'})
    td.append({'category' : 'size', 'code' : 'W2', 'name' : '2 Watt'})
    td.append({'category' : 'size', 'code' : 'W3', 'name' : '3 Watt'})
    td.append({'category' : 'size', 'code' : 'W4', 'name' : '4 Watt'})
    td.append({'category' : 'size', 'code' : 'W5', 'name' : '5 Watt'})
    td.append({'category' : 'size', 'code' : 'W6', 'name' : '6 Watt'})
    td.append({'category' : 'size', 'code' : 'W7', 'name' : '7 Watt'})
    td.append({'category' : 'size', 'code' : 'W8', 'name' : '8 Watt'})
    td.append({'category' : 'size', 'code' : 'W9', 'name' : '9 Watt'})
    td.append({'category' : 'size', 'code' : 'W10', 'name' : '10 Watt'})
    td.append({'category' : 'size', 'code' : 'W11', 'name' : '11 Watt'})
    td.append({'category' : 'size', 'code' : 'W12', 'name' : '12 Watt'})
    td.append({'category' : 'size', 'code' : 'W13', 'name' : '13 Watt'})
    td.append({'category' : 'size', 'code' : 'W14', 'name' : '14 Watt'})
    td.append({'category' : 'size', 'code' : 'W15', 'name' : '15 Watt'})
    td.append({'category' : 'size', 'code' : 'W16', 'name' : '16 Watt'})
    td.append({'category' : 'size', 'code' : 'W17', 'name' : '17 Watt'})
    td.append({'category' : 'size', 'code' : 'W18', 'name' : '18 Watt'})
    td.append({'category' : 'size', 'code' : 'W19', 'name' : '19 Watt'})
    td.append({'category' : 'size', 'code' : 'W20', 'name' : '20 Watt'})
    td.append({'category' : 'size', 'code' : 'W21', 'name' : '21 Watt'})
    td.append({'category' : 'size', 'code' : 'W22', 'name' : '22 Watt'})
    td.append({'category' : 'size', 'code' : 'W23', 'name' : '23 Watt'})
    td.append({'category' : 'size', 'code' : 'W24', 'name' : '24 Watt'})
    td.append({'category' : 'size', 'code' : 'W25', 'name' : '25 Watt'})
    td.append({'category' : 'size', 'code' : 'W26', 'name' : '26 Watt'})
    td.append({'category' : 'size', 'code' : 'W27', 'name' : '27 Watt'})
    td.append({'category' : 'size', 'code' : 'W28', 'name' : '28 Watt'})
    td.append({'category' : 'size', 'code' : 'W29', 'name' : '29 Watt'})
    td.append({'category' : 'size', 'code' : 'W30', 'name' : '30 Watt'})
    td.append({'category' : 'size', 'code' : 'W31', 'name' : '31 Watt'})
    td.append({'category' : 'size', 'code' : 'W32', 'name' : '32 Watt'})
    td.append({'category' : 'size', 'code' : 'W33', 'name' : '33 Watt'})
    td.append({'category' : 'size', 'code' : 'W34', 'name' : '34 Watt'})
    td.append({'category' : 'size', 'code' : 'W35', 'name' : '35 Watt'})
    td.append({'category' : 'size', 'code' : 'W36', 'name' : '36 Watt'})
    td.append({'category' : 'size', 'code' : 'W37', 'name' : '37 Watt'})
    td.append({'category' : 'size', 'code' : 'W38', 'name' : '38 Watt'})
    td.append({'category' : 'size', 'code' : 'W39', 'name' : '39 Watt'})
    td.append({'category' : 'size', 'code' : 'W40', 'name' : '40 Watt'})
    td.append({'category' : 'size', 'code' : 'W41', 'name' : '41 Watt'})
    td.append({'category' : 'size', 'code' : 'W42', 'name' : '42 Watt'})
    td.append({'category' : 'size', 'code' : 'W43', 'name' : '43 Watt'})
    td.append({'category' : 'size', 'code' : 'W44', 'name' : '44 Watt'})
    td.append({'category' : 'size', 'code' : 'W45', 'name' : '45 Watt'})
    td.append({'category' : 'size', 'code' : 'W46', 'name' : '46 Watt'})
    td.append({'category' : 'size', 'code' : 'W47', 'name' : '47 Watt'})
    td.append({'category' : 'size', 'code' : 'W48', 'name' : '48 Watt'})
    td.append({'category' : 'size', 'code' : 'W49', 'name' : '49 Watt'})
    td.append({'category' : 'size', 'code' : 'W50', 'name' : '50 Watt'})
    td.append({'category' : 'size', 'code' : 'W51', 'name' : '51 Watt'})
    td.append({'category' : 'size', 'code' : 'W52', 'name' : '52 Watt'})
    td.append({'category' : 'size', 'code' : 'W53', 'name' : '53 Watt'})
    td.append({'category' : 'size', 'code' : 'W54', 'name' : '54 Watt'})
    td.append({'category' : 'size', 'code' : 'W55', 'name' : '55 Watt'})
    td.append({'category' : 'size', 'code' : 'W56', 'name' : '56 Watt'})
    td.append({'category' : 'size', 'code' : 'W57', 'name' : '57 Watt'})
    td.append({'category' : 'size', 'code' : 'W58', 'name' : '58 Watt'})
    td.append({'category' : 'size', 'code' : 'W59', 'name' : '59 Watt'})
    td.append({'category' : 'size', 'code' : 'W60', 'name' : '60 Watt'})
    td.append({'category' : 'size', 'code' : 'W61', 'name' : '61 Watt'})
    td.append({'category' : 'size', 'code' : 'W62', 'name' : '62 Watt'})
    td.append({'category' : 'size', 'code' : 'W63', 'name' : '63 Watt'})
    td.append({'category' : 'size', 'code' : 'W64', 'name' : '64 Watt'})
    td.append({'category' : 'size', 'code' : 'W65', 'name' : '65 Watt'})
    td.append({'category' : 'size', 'code' : 'W66', 'name' : '66 Watt'})
    td.append({'category' : 'size', 'code' : 'W67', 'name' : '67 Watt'})
    td.append({'category' : 'size', 'code' : 'W68', 'name' : '68 Watt'})
    td.append({'category' : 'size', 'code' : 'W69', 'name' : '69 Watt'})
    td.append({'category' : 'size', 'code' : 'W70', 'name' : '70 Watt'})
    td.append({'category' : 'size', 'code' : 'W71', 'name' : '71 Watt'})
    td.append({'category' : 'size', 'code' : 'W72', 'name' : '72 Watt'})
    td.append({'category' : 'size', 'code' : 'W73', 'name' : '73 Watt'})
    td.append({'category' : 'size', 'code' : 'W74', 'name' : '74 Watt'})
    td.append({'category' : 'size', 'code' : 'W75', 'name' : '75 Watt'})
    td.append({'category' : 'size', 'code' : 'W76', 'name' : '76 Watt'})
    td.append({'category' : 'size', 'code' : 'W77', 'name' : '77 Watt'})
    td.append({'category' : 'size', 'code' : 'W78', 'name' : '78 Watt'})
    td.append({'category' : 'size', 'code' : 'W79', 'name' : '79 Watt'})
    td.append({'category' : 'size', 'code' : 'W80', 'name' : '80 Watt'})
    td.append({'category' : 'size', 'code' : 'W81', 'name' : '81 Watt'})
    td.append({'category' : 'size', 'code' : 'W82', 'name' : '82 Watt'})
    td.append({'category' : 'size', 'code' : 'W83', 'name' : '83 Watt'})
    td.append({'category' : 'size', 'code' : 'W84', 'name' : '84 Watt'})
    td.append({'category' : 'size', 'code' : 'W85', 'name' : '85 Watt'})
    td.append({'category' : 'size', 'code' : 'W86', 'name' : '86 Watt'})
    td.append({'category' : 'size', 'code' : 'W87', 'name' : '87 Watt'})
    td.append({'category' : 'size', 'code' : 'W88', 'name' : '88 Watt'})
    td.append({'category' : 'size', 'code' : 'W89', 'name' : '89 Watt'})
    td.append({'category' : 'size', 'code' : 'W90', 'name' : '90 Watt'})
    td.append({'category' : 'size', 'code' : 'W91', 'name' : '91 Watt'})
    td.append({'category' : 'size', 'code' : 'W92', 'name' : '92 Watt'})
    td.append({'category' : 'size', 'code' : 'W93', 'name' : '93 Watt'})
    td.append({'category' : 'size', 'code' : 'W94', 'name' : '94 Watt'})
    td.append({'category' : 'size', 'code' : 'W95', 'name' : '95 Watt'})
    td.append({'category' : 'size', 'code' : 'W96', 'name' : '96 Watt'})
    td.append({'category' : 'size', 'code' : 'W97', 'name' : '97 Watt'})
    td.append({'category' : 'size', 'code' : 'W98', 'name' : '98 Watt'})
    td.append({'category' : 'size', 'code' : 'W99', 'name' : '99 Watt'})
    td.append({'category' : 'size', 'code' : 'TH', 'name' : ''})
    td.append({'category' : 'size', 'code' : 'SM', 'name' : ''})
    td.append({'category' : 'size', 'code' : 'ST', 'name' : 'Standard'})
    td.append({'category' : 'size', 'code' : 'MC', 'name' : 'Micro'})
    td.append({'category' : 'size', 'code' : 'MN', 'name' : 'Mini'})
    td.append({'category' : 'size', 'code' : 'TA', 'name' : 'Type A'})
    td.append({'category' : 'size', 'code' : 'TB', 'name' : 'Type B'})
    td.append({'category' : 'size', 'code' : 'TC', 'name' : 'Type C'})
    td.append({'category' : 'size', 'code' : 'SC', 'name' : 'Solid'})
    td.append({'category' : 'size', 'code' : '01D', 'name' : '0.1 mm'})
    td.append({'category' : 'size', 'code' : '02D', 'name' : '0.2 mm'})
    td.append({'category' : 'size', 'code' : '03D', 'name' : '0.3 mm'})
    td.append({'category' : 'size', 'code' : '04D', 'name' : '0.4 mm'})
    td.append({'category' : 'size', 'code' : '05D', 'name' : '0.5 mm'})
    td.append({'category' : 'size', 'code' : '06D', 'name' : '0.6 mm'})
    td.append({'category' : 'size', 'code' : '07D', 'name' : '0.7 mm'})
    td.append({'category' : 'size', 'code' : '08D', 'name' : '0.8 mm'})
    td.append({'category' : 'size', 'code' : '09D', 'name' : '0.9 mm'})
    td.append({'category' : 'size', 'code' : '10D', 'name' : '1 mm'})
    td.append({'category' : 'size', 'code' : '11D', 'name' : '1.1 mm'})
    td.append({'category' : 'size', 'code' : '12D', 'name' : '1.2 mm'})
    td.append({'category' : 'size', 'code' : '13D', 'name' : '1.3 mm'})
    td.append({'category' : 'size', 'code' : '14D', 'name' : '1.4 mm'})
    td.append({'category' : 'size', 'code' : '15D', 'name' : '1.5 mm'})
    td.append({'category' : 'size', 'code' : '16D', 'name' : '1.6 mm'})
    td.append({'category' : 'size', 'code' : '17D', 'name' : '1.7 mm'})
    td.append({'category' : 'size', 'code' : '175D', 'name' : '1.75 mm'})
    td.append({'category' : 'size', 'code' : '18D', 'name' : '1.8 mm'})
    td.append({'category' : 'size', 'code' : '19D', 'name' : '1.9 mm'})
    td.append({'category' : 'size', 'code' : '20D', 'name' : '2 mm'})
    td.append({'category' : 'size', 'code' : '21D', 'name' : '2.1 mm'})
    td.append({'category' : 'size', 'code' : '22D', 'name' : '2.2 mm'})
    td.append({'category' : 'size', 'code' : '23D', 'name' : '2.3 mm'})
    td.append({'category' : 'size', 'code' : '24D', 'name' : '2.4 mm'})
    td.append({'category' : 'size', 'code' : '25D', 'name' : '2.5 mm'})
    td.append({'category' : 'size', 'code' : '26D', 'name' : '2.6 mm'})
    td.append({'category' : 'size', 'code' : '27D', 'name' : '2.7 mm'})
    td.append({'category' : 'size', 'code' : '28D', 'name' : '2.8 mm'})
    td.append({'category' : 'size', 'code' : '29D', 'name' : '2.9 mm'})
    td.append({'category' : 'size', 'code' : '30D', 'name' : '3.0 mm'})
    td.append({'category' : 'size', 'code' : '35D', 'name' : '3.5 mm'})
    td.append({'category' : 'size', 'code' : '36D', 'name' : '3.6 mm'})
    td.append({'category' : 'size', 'code' : '45D', 'name' : '4.5 mm'})
    td.append({'category' : 'size', 'code' : '55D', 'name' : '5.5 mm'})
    td.append({'category' : 'size', 'code' : '63D', 'name' : '6.3 mm'})
    td.append({'category' : 'size', 'code' : '81D', 'name' : '8.1 mm'})
    td.append({'category' : 'size', 'code' : 'I05D', 'name' : '1.27 mm'})
    td.append({'category' : 'size', 'code' : 'I01', 'name' : '2.54 mm'})
    td.append({'category' : 'size', 'code' : 'I02', 'name' : '5.08 mm'})
    td.append({'category' : 'size', 'code' : 'I03', 'name' : '7.62 mm'})
    td.append({'category' : 'size', 'code' : 'I04', 'name' : '10.16 mm'})
    td.append({'category' : 'size', 'code' : 'I05', 'name' : '12.7 mm'})
    td.append({'category' : 'size', 'code' : 'I06', 'name' : '15.24 mm'})
    td.append({'category' : 'size', 'code' : 'I07', 'name' : '17.78 mm'})
    td.append({'category' : 'size', 'code' : 'I08', 'name' : '20.32 mm'})
    td.append({'category' : 'size', 'code' : 'I09', 'name' : '22.86 mm'})
    td.append({'category' : 'size', 'code' : '01', 'name' : '1 mm'})
    td.append({'category' : 'size', 'code' : '02', 'name' : '2 mm'})
    td.append({'category' : 'size', 'code' : '03', 'name' : '3 mm'})
    td.append({'category' : 'size', 'code' : '39D', 'name' : '3.9 mm'})
    td.append({'category' : 'size', 'code' : '04', 'name' : '4 mm'})
    td.append({'category' : 'size', 'code' : '05', 'name' : '5 mm'})
    td.append({'category' : 'size', 'code' : '52D', 'name' : '5.2 mm'})
    td.append({'category' : 'size', 'code' : '06', 'name' : '6 mm'})
    td.append({'category' : 'size', 'code' : 'S63D', 'name' : 'SMD (6.3 mm)'})
    td.append({'category' : 'size', 'code' : '65D', 'name' : '6.5 mm'})
    td.append({'category' : 'size', 'code' : '07', 'name' : '7 mm'})
    td.append({'category' : 'size', 'code' : 'S21D', 'name' : '2.1 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S05', 'name' : '5 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S06', 'name' : '6 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S07', 'name' : '7 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S08', 'name' : '8 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S09', 'name' : '9 mm (SMD)'})
    td.append({'category' : 'size', 'code' : 'S10', 'name' : '10 mm (SMD)'})
    td.append({'category' : 'size', 'code' : '08', 'name' : '8 mm'})
    td.append({'category' : 'size', 'code' : '88D', 'name' : '8.8 mm'})
    td.append({'category' : 'size', 'code' : '09', 'name' : '9 mm'})
    td.append({'category' : 'size', 'code' : '92D', 'name' : '9.2 mm'})
    td.append({'category' : 'size', 'code' : '95D', 'name' : '9.5 mm'})
    td.append({'category' : 'size', 'code' : '97D', 'name' : '9.7 mm'})
    td.append({'category' : 'size', 'code' : '98D', 'name' : '9.8 mm'})
    td.append({'category' : 'size', 'code' : '10', 'name' : '10 mm'})
    td.append({'category' : 'size', 'code' : '11', 'name' : '11 mm'})
    td.append({'category' : 'size', 'code' : '12', 'name' : '12 mm'})
    td.append({'category' : 'size', 'code' : '13', 'name' : '13 mm'})
    td.append({'category' : 'size', 'code' : '14', 'name' : '14 mm'})
    td.append({'category' : 'size', 'code' : '15', 'name' : '15 mm'})
    td.append({'category' : 'size', 'code' : '155D', 'name' : '15.5 mm'})
    td.append({'category' : 'size', 'code' : '16', 'name' : '16 mm'})
    td.append({'category' : 'size', 'code' : '17', 'name' : '17 mm'})
    td.append({'category' : 'size', 'code' : '18', 'name' : '18 mm'})
    td.append({'category' : 'size', 'code' : '19', 'name' : '19 mm'})
    td.append({'category' : 'size', 'code' : '64DX49S', 'name' : '6.4 x 4.9 mm'})
    td.append({'category' : 'size', 'code' : '81DX42S', 'name' : '8.1 x 4.2 mm'})
    td.append({'category' : 'size', 'code' : '87DX45D', 'name' : '8.7 mm x 4.5 mm'})
    td.append({'category' : 'size', 'code' : '19X15', 'name' : '19 x 15 mm'})
    td.append({'category' : 'size', 'code' : '25X13', 'name' : '25 x 13 mm'})
    td.append({'category' : 'size', 'code' : '20', 'name' : '20 mm'})
    td.append({'category' : 'size', 'code' : '21', 'name' : '21 mm'})
    td.append({'category' : 'size', 'code' : '22', 'name' : '22 mm'})
    td.append({'category' : 'size', 'code' : '23', 'name' : '23 mm'})
    td.append({'category' : 'size', 'code' : '24', 'name' : '24 mm'})
    td.append({'category' : 'size', 'code' : '25', 'name' : '25 mm'})
    td.append({'category' : 'size', 'code' : '26', 'name' : '26 mm'})
    td.append({'category' : 'size', 'code' : '27', 'name' : '27 mm'})
    td.append({'category' : 'size', 'code' : '28', 'name' : '28 mm'})
    td.append({'category' : 'size', 'code' : '29', 'name' : '29 mm'})
    td.append({'category' : 'size', 'code' : '30', 'name' : '30 mm'})
    td.append({'category' : 'size', 'code' : '31', 'name' : '31 mm'})
    td.append({'category' : 'size', 'code' : '32', 'name' : '32 mm'})
    td.append({'category' : 'size', 'code' : '33', 'name' : '33 mm'})
    td.append({'category' : 'size', 'code' : '34', 'name' : '34 mm'})
    td.append({'category' : 'size', 'code' : '35', 'name' : '35 mm'})
    td.append({'category' : 'size', 'code' : '36', 'name' : '36 mm'})
    td.append({'category' : 'size', 'code' : '37', 'name' : '37 mm'})
    td.append({'category' : 'size', 'code' : '38', 'name' : '38 mm'})
    td.append({'category' : 'size', 'code' : '39', 'name' : '39 mm'})
    td.append({'category' : 'size', 'code' : '40', 'name' : '40 mm'})
    td.append({'category' : 'size', 'code' : '41', 'name' : '41 mm'})
    td.append({'category' : 'size', 'code' : '42', 'name' : '42 mm'})
    td.append({'category' : 'size', 'code' : '43', 'name' : '43 mm'})
    td.append({'category' : 'size', 'code' : '44', 'name' : '44 mm'})
    td.append({'category' : 'size', 'code' : '45', 'name' : '45 mm'})
    td.append({'category' : 'size', 'code' : '46', 'name' : '46 mm'})
    td.append({'category' : 'size', 'code' : '47', 'name' : '47 mm'})
    td.append({'category' : 'size', 'code' : '48', 'name' : '48 mm'})
    td.append({'category' : 'size', 'code' : '49', 'name' : '49 mm'})
    td.append({'category' : 'size', 'code' : '50', 'name' : '50 mm'})
    td.append({'category' : 'size', 'code' : '51', 'name' : '51 mm'})
    td.append({'category' : 'size', 'code' : '52', 'name' : '52 mm'})
    td.append({'category' : 'size', 'code' : '53', 'name' : '53 mm'})
    td.append({'category' : 'size', 'code' : '54', 'name' : '54 mm'})
    td.append({'category' : 'size', 'code' : '55', 'name' : '55 mm'})
    td.append({'category' : 'size', 'code' : '56', 'name' : '56 mm'})
    td.append({'category' : 'size', 'code' : '57', 'name' : '57 mm'})
    td.append({'category' : 'size', 'code' : '58', 'name' : '58 mm'})
    td.append({'category' : 'size', 'code' : '59', 'name' : '59 mm'})
    td.append({'category' : 'size', 'code' : '60', 'name' : '60 mm'})
    td.append({'category' : 'size', 'code' : '61', 'name' : '61 mm'})
    td.append({'category' : 'size', 'code' : '62', 'name' : '62 mm'})
    td.append({'category' : 'size', 'code' : '63', 'name' : '63 mm'})
    td.append({'category' : 'size', 'code' : '64', 'name' : '64 mm'})
    td.append({'category' : 'size', 'code' : '65', 'name' : '65 mm'})
    td.append({'category' : 'size', 'code' : '66', 'name' : '66 mm'})
    td.append({'category' : 'size', 'code' : '67', 'name' : '67 mm'})
    td.append({'category' : 'size', 'code' : '68', 'name' : '68 mm'})
    td.append({'category' : 'size', 'code' : '69', 'name' : '69 mm'})
    td.append({'category' : 'size', 'code' : '70', 'name' : '70 mm'})
    td.append({'category' : 'size', 'code' : '71', 'name' : '71 mm'})
    td.append({'category' : 'size', 'code' : '72', 'name' : '72 mm'})
    td.append({'category' : 'size', 'code' : '73', 'name' : '73 mm'})
    td.append({'category' : 'size', 'code' : '74', 'name' : '74 mm'})
    td.append({'category' : 'size', 'code' : '75', 'name' : '75 mm'})
    td.append({'category' : 'size', 'code' : '76', 'name' : '76 mm'})
    td.append({'category' : 'size', 'code' : '77', 'name' : '77 mm'})
    td.append({'category' : 'size', 'code' : '78', 'name' : '78 mm'})
    td.append({'category' : 'size', 'code' : '79', 'name' : '79 mm'})
    td.append({'category' : 'size', 'code' : '80', 'name' : '80 mm'})
    td.append({'category' : 'size', 'code' : '81', 'name' : '81 mm'})
    td.append({'category' : 'size', 'code' : '82', 'name' : '82 mm'})
    td.append({'category' : 'size', 'code' : '83', 'name' : '83 mm'})
    td.append({'category' : 'size', 'code' : '84', 'name' : '84 mm'})
    td.append({'category' : 'size', 'code' : '85', 'name' : '85 mm'})
    td.append({'category' : 'size', 'code' : '86', 'name' : '86 mm'})
    td.append({'category' : 'size', 'code' : '87', 'name' : '87 mm'})
    td.append({'category' : 'size', 'code' : '88', 'name' : '88 mm'})
    td.append({'category' : 'size', 'code' : '89', 'name' : '89 mm'})
    td.append({'category' : 'size', 'code' : '90', 'name' : '90 mm'})
    td.append({'category' : 'size', 'code' : '91', 'name' : '91 mm'})
    td.append({'category' : 'size', 'code' : '92', 'name' : '92 mm'})
    td.append({'category' : 'size', 'code' : '93', 'name' : '93 mm'})
    td.append({'category' : 'size', 'code' : '94', 'name' : '94 mm'})
    td.append({'category' : 'size', 'code' : '95', 'name' : '95 mm'})
    td.append({'category' : 'size', 'code' : '96', 'name' : '96 mm'})
    td.append({'category' : 'size', 'code' : '97', 'name' : '97 mm'})
    td.append({'category' : 'size', 'code' : '98', 'name' : '98 mm'})
    td.append({'category' : 'size', 'code' : '99', 'name' : '99 mm'})
    td.append({'category' : 'size', 'code' : '100', 'name' : '100 mm'})
    td.append({'category' : 'size', 'code' : '101', 'name' : '101 mm'})
    td.append({'category' : 'size', 'code' : '102', 'name' : '102 mm'})
    td.append({'category' : 'size', 'code' : '103', 'name' : '103 mm'})
    td.append({'category' : 'size', 'code' : '104', 'name' : '104 mm'})
    td.append({'category' : 'size', 'code' : '105', 'name' : '105 mm'})
    td.append({'category' : 'size', 'code' : '106', 'name' : '106 mm'})
    td.append({'category' : 'size', 'code' : '107', 'name' : '107 mm'})
    td.append({'category' : 'size', 'code' : '108', 'name' : '108 mm'})
    td.append({'category' : 'size', 'code' : '109', 'name' : '109 mm'})
    td.append({'category' : 'size', 'code' : '110', 'name' : '110 mm'})
    td.append({'category' : 'size', 'code' : '111', 'name' : '111 mm'})
    td.append({'category' : 'size', 'code' : '112', 'name' : '112 mm'})
    td.append({'category' : 'size', 'code' : '113', 'name' : '113 mm'})
    td.append({'category' : 'size', 'code' : '114', 'name' : '114 mm'})
    td.append({'category' : 'size', 'code' : '115', 'name' : '115 mm'})
    td.append({'category' : 'size', 'code' : '116', 'name' : '116 mm'})
    td.append({'category' : 'size', 'code' : '117', 'name' : '117 mm'})
    td.append({'category' : 'size', 'code' : '118', 'name' : '118 mm'})
    td.append({'category' : 'size', 'code' : '119', 'name' : '119 mm'})
    td.append({'category' : 'size', 'code' : '120', 'name' : '120 mm'})
    td.append({'category' : 'size', 'code' : '121', 'name' : '121 mm'})
    td.append({'category' : 'size', 'code' : '122', 'name' : '122 mm'})
    td.append({'category' : 'size', 'code' : '123', 'name' : '123 mm'})
    td.append({'category' : 'size', 'code' : '124', 'name' : '124 mm'})
    td.append({'category' : 'size', 'code' : '125', 'name' : '125 mm'})
    td.append({'category' : 'size', 'code' : '126', 'name' : '126 mm'})
    td.append({'category' : 'size', 'code' : '127', 'name' : '127 mm'})
    td.append({'category' : 'size', 'code' : '128', 'name' : '128 mm'})
    td.append({'category' : 'size', 'code' : '129', 'name' : '129 mm'})
    td.append({'category' : 'size', 'code' : '130', 'name' : '130 mm'})
    td.append({'category' : 'size', 'code' : '131', 'name' : '131 mm'})
    td.append({'category' : 'size', 'code' : '132', 'name' : '132 mm'})
    td.append({'category' : 'size', 'code' : '133', 'name' : '133 mm'})
    td.append({'category' : 'size', 'code' : '134', 'name' : '134 mm'})
    td.append({'category' : 'size', 'code' : '135', 'name' : '135 mm'})
    td.append({'category' : 'size', 'code' : '136', 'name' : '136 mm'})
    td.append({'category' : 'size', 'code' : '137', 'name' : '137 mm'})
    td.append({'category' : 'size', 'code' : '138', 'name' : '138 mm'})
    td.append({'category' : 'size', 'code' : '139', 'name' : '139 mm'})
    td.append({'category' : 'size', 'code' : '140', 'name' : '140 mm'})
    td.append({'category' : 'size', 'code' : '141', 'name' : '141 mm'})
    td.append({'category' : 'size', 'code' : '142', 'name' : '142 mm'})
    td.append({'category' : 'size', 'code' : '143', 'name' : '143 mm'})
    td.append({'category' : 'size', 'code' : '144', 'name' : '144 mm'})
    td.append({'category' : 'size', 'code' : '145', 'name' : '145 mm'})
    td.append({'category' : 'size', 'code' : '146', 'name' : '146 mm'})
    td.append({'category' : 'size', 'code' : '147', 'name' : '147 mm'})
    td.append({'category' : 'size', 'code' : '148', 'name' : '148 mm'})
    td.append({'category' : 'size', 'code' : '149', 'name' : '149 mm'})
    td.append({'category' : 'size', 'code' : '150', 'name' : '150 mm'})
    td.append({'category' : 'size', 'code' : '151', 'name' : '151 mm'})
    td.append({'category' : 'size', 'code' : '152', 'name' : '152 mm'})
    td.append({'category' : 'size', 'code' : '153', 'name' : '153 mm'})
    td.append({'category' : 'size', 'code' : '154', 'name' : '154 mm'})
    td.append({'category' : 'size', 'code' : '155', 'name' : '155 mm'})
    td.append({'category' : 'size', 'code' : '156', 'name' : '156 mm'})
    td.append({'category' : 'size', 'code' : '157', 'name' : '157 mm'})
    td.append({'category' : 'size', 'code' : '158', 'name' : '158 mm'})
    td.append({'category' : 'size', 'code' : '159', 'name' : '159 mm'})
    td.append({'category' : 'size', 'code' : '160', 'name' : '160 mm'})
    td.append({'category' : 'size', 'code' : '161', 'name' : '161 mm'})
    td.append({'category' : 'size', 'code' : '162', 'name' : '162 mm'})
    td.append({'category' : 'size', 'code' : '163', 'name' : '163 mm'})
    td.append({'category' : 'size', 'code' : '164', 'name' : '164 mm'})
    td.append({'category' : 'size', 'code' : '165', 'name' : '165 mm'})
    td.append({'category' : 'size', 'code' : '166', 'name' : '166 mm'})
    td.append({'category' : 'size', 'code' : '167', 'name' : '167 mm'})
    td.append({'category' : 'size', 'code' : '168', 'name' : '168 mm'})
    td.append({'category' : 'size', 'code' : '169', 'name' : '169 mm'})
    td.append({'category' : 'size', 'code' : '170', 'name' : '170 mm'})
    td.append({'category' : 'size', 'code' : '171', 'name' : '171 mm'})
    td.append({'category' : 'size', 'code' : '172', 'name' : '172 mm'})
    td.append({'category' : 'size', 'code' : '173', 'name' : '173 mm'})
    td.append({'category' : 'size', 'code' : '174', 'name' : '174 mm'})
    td.append({'category' : 'size', 'code' : '175', 'name' : '175 mm'})
    td.append({'category' : 'size', 'code' : '176', 'name' : '176 mm'})
    td.append({'category' : 'size', 'code' : '177', 'name' : '177 mm'})
    td.append({'category' : 'size', 'code' : '178', 'name' : '178 mm'})
    td.append({'category' : 'size', 'code' : '179', 'name' : '179 mm'})
    td.append({'category' : 'size', 'code' : '180', 'name' : '180 mm'})
    td.append({'category' : 'size', 'code' : '181', 'name' : '181 mm'})
    td.append({'category' : 'size', 'code' : '182', 'name' : '182 mm'})
    td.append({'category' : 'size', 'code' : '183', 'name' : '183 mm'})
    td.append({'category' : 'size', 'code' : '184', 'name' : '184 mm'})
    td.append({'category' : 'size', 'code' : '185', 'name' : '185 mm'})
    td.append({'category' : 'size', 'code' : '186', 'name' : '186 mm'})
    td.append({'category' : 'size', 'code' : '187', 'name' : '187 mm'})
    td.append({'category' : 'size', 'code' : '188', 'name' : '188 mm'})
    td.append({'category' : 'size', 'code' : '189', 'name' : '189 mm'})
    td.append({'category' : 'size', 'code' : '190', 'name' : '190 mm'})
    td.append({'category' : 'size', 'code' : '191', 'name' : '191 mm'})
    td.append({'category' : 'size', 'code' : '192', 'name' : '192 mm'})
    td.append({'category' : 'size', 'code' : '193', 'name' : '193 mm'})
    td.append({'category' : 'size', 'code' : '194', 'name' : '194 mm'})
    td.append({'category' : 'size', 'code' : '195', 'name' : '195 mm'})
    td.append({'category' : 'size', 'code' : '196', 'name' : '196 mm'})
    td.append({'category' : 'size', 'code' : '197', 'name' : '197 mm'})
    td.append({'category' : 'size', 'code' : '198', 'name' : '198 mm'})
    td.append({'category' : 'size', 'code' : '199', 'name' : '199 mm'})
    td.append({'category' : 'size', 'code' : '200', 'name' : '200 mm'})
    td.append({'category' : 'size', 'code' : '201', 'name' : '201 mm'})
    td.append({'category' : 'size', 'code' : '202', 'name' : '202 mm'})
    td.append({'category' : 'size', 'code' : '203', 'name' : '203 mm'})
    td.append({'category' : 'size', 'code' : '204', 'name' : '204 mm'})
    td.append({'category' : 'size', 'code' : '205', 'name' : '205 mm'})
    td.append({'category' : 'size', 'code' : '206', 'name' : '206 mm'})
    td.append({'category' : 'size', 'code' : '207', 'name' : '207 mm'})
    td.append({'category' : 'size', 'code' : '208', 'name' : '208 mm'})
    td.append({'category' : 'size', 'code' : '209', 'name' : '209 mm'})
    td.append({'category' : 'size', 'code' : '210', 'name' : '210 mm'})
    td.append({'category' : 'size', 'code' : '211', 'name' : '211 mm'})
    td.append({'category' : 'size', 'code' : '212', 'name' : '212 mm'})
    td.append({'category' : 'size', 'code' : '213', 'name' : '213 mm'})
    td.append({'category' : 'size', 'code' : '214', 'name' : '214 mm'})
    td.append({'category' : 'size', 'code' : '215', 'name' : '215 mm'})
    td.append({'category' : 'size', 'code' : '216', 'name' : '216 mm'})
    td.append({'category' : 'size', 'code' : '217', 'name' : '217 mm'})
    td.append({'category' : 'size', 'code' : '218', 'name' : '218 mm'})
    td.append({'category' : 'size', 'code' : '219', 'name' : '219 mm'})
    td.append({'category' : 'size', 'code' : '220', 'name' : '220 mm'})
    td.append({'category' : 'size', 'code' : '221', 'name' : '221 mm'})
    td.append({'category' : 'size', 'code' : '222', 'name' : '222 mm'})
    td.append({'category' : 'size', 'code' : '223', 'name' : '223 mm'})
    td.append({'category' : 'size', 'code' : '224', 'name' : '224 mm'})
    td.append({'category' : 'size', 'code' : '225', 'name' : '225 mm'})
    td.append({'category' : 'size', 'code' : '226', 'name' : '226 mm'})
    td.append({'category' : 'size', 'code' : '227', 'name' : '227 mm'})
    td.append({'category' : 'size', 'code' : '228', 'name' : '228 mm'})
    td.append({'category' : 'size', 'code' : '229', 'name' : '229 mm'})
    td.append({'category' : 'size', 'code' : '230', 'name' : '230 mm'})
    td.append({'category' : 'size', 'code' : '231', 'name' : '231 mm'})
    td.append({'category' : 'size', 'code' : '232', 'name' : '232 mm'})
    td.append({'category' : 'size', 'code' : '233', 'name' : '233 mm'})
    td.append({'category' : 'size', 'code' : '234', 'name' : '234 mm'})
    td.append({'category' : 'size', 'code' : '235', 'name' : '235 mm'})
    td.append({'category' : 'size', 'code' : '236', 'name' : '236 mm'})
    td.append({'category' : 'size', 'code' : '237', 'name' : '237 mm'})
    td.append({'category' : 'size', 'code' : '238', 'name' : '238 mm'})
    td.append({'category' : 'size', 'code' : '239', 'name' : '239 mm'})
    td.append({'category' : 'size', 'code' : '240', 'name' : '240 mm'})
    td.append({'category' : 'size', 'code' : '241', 'name' : '241 mm'})
    td.append({'category' : 'size', 'code' : '242', 'name' : '242 mm'})
    td.append({'category' : 'size', 'code' : '243', 'name' : '243 mm'})
    td.append({'category' : 'size', 'code' : '244', 'name' : '244 mm'})
    td.append({'category' : 'size', 'code' : '245', 'name' : '245 mm'})
    td.append({'category' : 'size', 'code' : '246', 'name' : '246 mm'})
    td.append({'category' : 'size', 'code' : '247', 'name' : '247 mm'})
    td.append({'category' : 'size', 'code' : '248', 'name' : '248 mm'})
    td.append({'category' : 'size', 'code' : '249', 'name' : '249 mm'})
    td.append({'category' : 'size', 'code' : '250', 'name' : '250 mm'})
    td.append({'category' : 'size', 'code' : '1W', 'name' : '1 Wire'})
    td.append({'category' : 'size', 'code' : '2W', 'name' : '2 Wire'})
    td.append({'category' : 'size', 'code' : '3W', 'name' : '3 Wire'})
    td.append({'category' : 'size', 'code' : '4W', 'name' : '4 Wire'})
    td.append({'category' : 'size', 'code' : '5W', 'name' : '5 Wire'})
    td.append({'category' : 'size', 'code' : '6W', 'name' : '6 Wire'})
    td.append({'category' : 'size', 'code' : '7W', 'name' : '7 Wire'})
    td.append({'category' : 'size', 'code' : '8W', 'name' : '8 Wire'})
    td.append({'category' : 'size', 'code' : '9W', 'name' : '9 Wire'})
    td.append({'category' : 'size', 'code' : '10W', 'name' : '10 Wire'})
    td.append({'category' : 'size', 'code' : '11W', 'name' : '11 Wire'})
    td.append({'category' : 'size', 'code' : '12W', 'name' : '12 Wire'})
    td.append({'category' : 'size', 'code' : '13W', 'name' : '13 Wire'})
    td.append({'category' : 'size', 'code' : '14W', 'name' : '14 Wire'})
    td.append({'category' : 'size', 'code' : '15W', 'name' : '15 Wire'})
    td.append({'category' : 'size', 'code' : '16W', 'name' : '16 Wire'})
    td.append({'category' : 'size', 'code' : '17W', 'name' : '17 Wire'})
    td.append({'category' : 'size', 'code' : '18W', 'name' : '18 Wire'})
    td.append({'category' : 'size', 'code' : '19W', 'name' : '19 Wire'})
    td.append({'category' : 'size', 'code' : '20W', 'name' : '20 Wire'})
    td.append({'category' : 'size', 'code' : '21W', 'name' : '21 Wire'})
    td.append({'category' : 'size', 'code' : '22W', 'name' : '22 Wire'})
    td.append({'category' : 'size', 'code' : '23W', 'name' : '23 Wire'})
    td.append({'category' : 'size', 'code' : '24W', 'name' : '24 Wire'})
    td.append({'category' : 'size', 'code' : '25W', 'name' : '25 Wire'})
    td.append({'category' : 'size', 'code' : '26W', 'name' : '26 Wire'})
    td.append({'category' : 'size', 'code' : '27W', 'name' : '27 Wire'})
    td.append({'category' : 'size', 'code' : '28W', 'name' : '28 Wire'})
    td.append({'category' : 'size', 'code' : '29W', 'name' : '29 Wire'})
    td.append({'category' : 'size', 'code' : '30W', 'name' : '30 Wire'})
    td.append({'category' : 'size', 'code' : '31W', 'name' : '31 Wire'})
    td.append({'category' : 'size', 'code' : '32W', 'name' : '32 Wire'})
    td.append({'category' : 'size', 'code' : '33W', 'name' : '33 Wire'})
    td.append({'category' : 'size', 'code' : '34W', 'name' : '34 Wire'})
    td.append({'category' : 'size', 'code' : '35W', 'name' : '35 Wire'})
    td.append({'category' : 'size', 'code' : '36W', 'name' : '36 Wire'})
    td.append({'category' : 'size', 'code' : '37W', 'name' : '37 Wire'})
    td.append({'category' : 'size', 'code' : '38W', 'name' : '38 Wire'})
    td.append({'category' : 'size', 'code' : '39W', 'name' : '39 Wire'})
    td.append({'category' : 'size', 'code' : '40W', 'name' : '40 Wire'})
    td.append({'category' : 'size', 'code' : '41W', 'name' : '41 Wire'})
    td.append({'category' : 'size', 'code' : '42W', 'name' : '42 Wire'})
    td.append({'category' : 'size', 'code' : '43W', 'name' : '43 Wire'})
    td.append({'category' : 'size', 'code' : '44W', 'name' : '44 Wire'})
    td.append({'category' : 'size', 'code' : '45W', 'name' : '45 Wire'})
    td.append({'category' : 'size', 'code' : '46W', 'name' : '46 Wire'})
    td.append({'category' : 'size', 'code' : '47W', 'name' : '47 Wire'})
    td.append({'category' : 'size', 'code' : '48W', 'name' : '48 Wire'})
    td.append({'category' : 'size', 'code' : '49W', 'name' : '49 Wire'})
    td.append({'category' : 'size', 'code' : '50W', 'name' : '50 Wire'})
    td.append({'category' : 'size', 'code' : '51W', 'name' : '51 Wire'})
    td.append({'category' : 'size', 'code' : '52W', 'name' : '52 Wire'})
    td.append({'category' : 'size', 'code' : '53W', 'name' : '53 Wire'})
    td.append({'category' : 'size', 'code' : '54W', 'name' : '54 Wire'})
    td.append({'category' : 'size', 'code' : '55W', 'name' : '55 Wire'})
    td.append({'category' : 'size', 'code' : '56W', 'name' : '56 Wire'})
    td.append({'category' : 'size', 'code' : '57W', 'name' : '57 Wire'})
    td.append({'category' : 'size', 'code' : '58W', 'name' : '58 Wire'})
    td.append({'category' : 'size', 'code' : '59W', 'name' : '59 Wire'})
    td.append({'category' : 'size', 'code' : '60W', 'name' : '60 Wire'})
    td.append({'category' : 'size', 'code' : '61W', 'name' : '61 Wire'})
    td.append({'category' : 'size', 'code' : '62W', 'name' : '62 Wire'})
    td.append({'category' : 'size', 'code' : '63W', 'name' : '63 Wire'})
    td.append({'category' : 'size', 'code' : '64W', 'name' : '64 Wire'})
    td.append({'category' : 'size', 'code' : '65W', 'name' : '65 Wire'})
    td.append({'category' : 'size', 'code' : '66W', 'name' : '66 Wire'})
    td.append({'category' : 'size', 'code' : '67W', 'name' : '67 Wire'})
    td.append({'category' : 'size', 'code' : '68W', 'name' : '68 Wire'})
    td.append({'category' : 'size', 'code' : '69W', 'name' : '69 Wire'})
    td.append({'category' : 'size', 'code' : '70W', 'name' : '70 Wire'})
    td.append({'category' : 'size', 'code' : '71W', 'name' : '71 Wire'})
    td.append({'category' : 'size', 'code' : '72W', 'name' : '72 Wire'})
    td.append({'category' : 'size', 'code' : '73W', 'name' : '73 Wire'})
    td.append({'category' : 'size', 'code' : '74W', 'name' : '74 Wire'})
    td.append({'category' : 'size', 'code' : '75W', 'name' : '75 Wire'})
    td.append({'category' : 'size', 'code' : '76W', 'name' : '76 Wire'})
    td.append({'category' : 'size', 'code' : '77W', 'name' : '77 Wire'})
    td.append({'category' : 'size', 'code' : '78W', 'name' : '78 Wire'})
    td.append({'category' : 'size', 'code' : '79W', 'name' : '79 Wire'})
    td.append({'category' : 'size', 'code' : '80W', 'name' : '80 Wire'})
    td.append({'category' : 'size', 'code' : '81W', 'name' : '81 Wire'})
    td.append({'category' : 'size', 'code' : '82W', 'name' : '82 Wire'})
    td.append({'category' : 'size', 'code' : '83W', 'name' : '83 Wire'})
    td.append({'category' : 'size', 'code' : '84W', 'name' : '84 Wire'})
    td.append({'category' : 'size', 'code' : '85W', 'name' : '85 Wire'})
    td.append({'category' : 'size', 'code' : '86W', 'name' : '86 Wire'})
    td.append({'category' : 'size', 'code' : '87W', 'name' : '87 Wire'})
    td.append({'category' : 'size', 'code' : '88W', 'name' : '88 Wire'})
    td.append({'category' : 'size', 'code' : '89W', 'name' : '89 Wire'})
    td.append({'category' : 'size', 'code' : '90W', 'name' : '90 Wire'})
    td.append({'category' : 'size', 'code' : '91W', 'name' : '91 Wire'})
    td.append({'category' : 'size', 'code' : '92W', 'name' : '92 Wire'})
    td.append({'category' : 'size', 'code' : '93W', 'name' : '93 Wire'})
    td.append({'category' : 'size', 'code' : '94W', 'name' : '94 Wire'})
    td.append({'category' : 'size', 'code' : '95W', 'name' : '95 Wire'})
    td.append({'category' : 'size', 'code' : '96W', 'name' : '96 Wire'})
    td.append({'category' : 'size', 'code' : '97W', 'name' : '97 Wire'})
    td.append({'category' : 'size', 'code' : '98W', 'name' : '98 Wire'})
    td.append({'category' : 'size', 'code' : '99W', 'name' : '99 Wire'})
    td.append({'category' : 'size', 'code' : 'M1', 'name' : 'M1'})
    td.append({'category' : 'size', 'code' : 'M2', 'name' : 'M2'})
    td.append({'category' : 'size', 'code' : 'M3', 'name' : 'M3'})
    td.append({'category' : 'size', 'code' : 'M4', 'name' : 'M4'})
    td.append({'category' : 'size', 'code' : 'M5', 'name' : 'M5'})
    td.append({'category' : 'size', 'code' : 'M6', 'name' : 'M6'})
    td.append({'category' : 'size', 'code' : 'M7', 'name' : 'M7'})
    td.append({'category' : 'size', 'code' : 'M8', 'name' : 'M8'})
    td.append({'category' : 'size', 'code' : 'M9', 'name' : 'M9'})
    td.append({'category' : 'size', 'code' : 'M10', 'name' : 'M10'})
    td.append({'category' : 'size', 'code' : 'M12', 'name' : 'M12'})
    td.append({'category' : 'size', 'code' : 'M15', 'name' : 'M15'})
    td.append({'category' : 'size', 'code' : 'M20', 'name' : 'M20'})
    td.append({'category' : 'size', 'code' : 'DI14', 'name' : '14 Pin DIP'})
    td.append({'category' : 'size', 'code' : 'DI16', 'name' : '16 Pin DIP'})
    td.append({'category' : 'size', 'code' : 'DI18', 'name' : '18 Pin DIP'})
    td.append({'category' : 'size', 'code' : 'DI28', 'name' : '28 Pin DIP'})
    td.append({'category' : 'size', 'code' : 'DI28W', 'name' : '28 Pin DIP (0.6")'})
    td.append({'category' : 'size', 'code' : 'SS16', 'name' : '16 Pin SMD (SSOP)'})
    td.append({'category' : 'size', 'code' : 'SS24', 'name' : '24 Pin SMD (SSOP)'})
    td.append({'category' : 'size', 'code' : 'SS28', 'name' : '28 Pin SMD (SSOP)'})
    td.append({'category' : 'size', 'code' : 'SP08', 'name' : '8 Pin SMD (SOP)'})
    td.append({'category' : 'size', 'code' : 'SP16', 'name' : '16 Pin SMD (SOP)'})
    td.append({'category' : 'size', 'code' : 'SP20', 'name' : '20 Pin SMD (SOP)'})
    td.append({'category' : 'size', 'code' : 'MS08', 'name' : '8 Pin SMD (MSOP)'})
    td.append({'category' : 'size', 'code' : 'QFN14', 'name' : '14 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'QFN16', 'name' : '16 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'QFN24', 'name' : '24 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'QFN28', 'name' : '28 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'QFN32', 'name' : '32 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'VQF32', 'name' : '32 Pin SMD (VQFN)'})
    td.append({'category' : 'size', 'code' : 'VQF44', 'name' : '44 Pin SMD (VQFN)'})
    td.append({'category' : 'size', 'code' : 'QFN48', 'name' : '48 Pin SMD (QFN)'})
    td.append({'category' : 'size', 'code' : 'HQFN33', 'name' : '33 Pin SMD (Heatsink QFN)'})
    td.append({'category' : 'size', 'code' : 'QFP32', 'name' : '32 Pin SMD (TQFP)'})
    td.append({'category' : 'size', 'code' : 'QFP64', 'name' : '64 Pin SMD (TQFP)'})
    td.append({'category' : 'size', 'code' : 'QFP44', 'name' : '44 Pin SMD (TQFP)'})
    td.append({'category' : 'size', 'code' : 'QFP100', 'name' : '100 Pin SMD (TQFP)'})
    td.append({'category' : 'size', 'code' : 'LG14', 'name' : '14 Pin SMD (LGA)'})
    td.append({'category' : 'size', 'code' : 'ML14', 'name' : '14 Pin SMD (MLF)'})
    td.append({'category' : 'size', 'code' : 'ML32', 'name' : '32 Pin SMD (MLF)'})
    td.append({'category' : 'size', 'code' : 'MLP28', 'name' : '28 Pin SMD (MLP)'})
    td.append({'category' : 'size', 'code' : 'TS14', 'name' : '14 Pin SMD (TSSOP)'})
    td.append({'category' : 'size', 'code' : 'TS20', 'name' : '20 Pin SMD (TSSOP)'})
    td.append({'category' : 'size', 'code' : 'TS24', 'name' : '24 Pin SMD (TSSOP)'})
    td.append({'category' : 'size', 'code' : '128X64', 'name' : '128 x 64 Pixels'})
    td.append({'category' : 'size', 'code' : '16X2', 'name' : '16 x 2 Character'})
    td.append({'category' : 'size', 'code' : '7SEL', 'name' : '7 Segment LED'})
    td.append({'category' : 'size', 'code' : '10SEL', 'name' : '10 Segment LED Bargraph'})
    td.append({'category' : 'size', 'code' : 'RJ45', 'name' : '128 x 64 Pixels'})
    td.append({'category' : 'size', 'code' : 'DB09', 'name' : 'DB9'})
    td.append({'category' : 'size', 'code' : 'DB15', 'name' : 'DB15'})
    td.append({'category' : 'size', 'code' : 'DB25', 'name' : 'DB25'})
    td.append({'category' : 'size', 'code' : 'ACUS', 'name' : 'American Style (120v)'})
    td.append({'category' : 'size', 'code' : 'SMA', 'name' : 'SMA'})
    td.append({'category' : 'size', 'code' : 'L169W130H18', 'name' : '169 mm x 130 mm x 18 mm'})
    td.append({'category' : 'size', 'code' : 'SZ130', 'name' : '130 Size'})
    td.append({'category' : 'size', 'code' : 'DPAK', 'name' : 'DPAK'})
    td.append({'category' : 'size', 'code' : 'SO8', 'name' : 'SO-8'})
    td.append({'category' : 'size', 'code' : 'XHP70', 'name' : 'XHP 70'})
    td.append({'category' : 'size', 'code' : 'JSTXH', 'name' : 'JST XH (2.5 mm)'})
    td.append({'category' : 'size', 'code' : 'JSTSH', 'name' : 'JST XH (1 mm)'})
    td.append({'category' : 'size', 'code' : 'ADAF', 'name' : 'Adafruit'})
    td.append({'category' : 'size', 'code' : 'ARDC', 'name' : 'Compatible Arduino'})
    td.append({'category' : 'size', 'code' : 'ARDU', 'name' : 'Arduino'})
    td.append({'category' : 'size', 'code' : 'OOML', 'name' : 'Oomlout'})
    td.append({'category' : 'size', 'code' : 'RASP', 'name' : 'Raspberry Pi Foundation'})
    td.append({'category' : 'size', 'code' : 'SEEE', 'name' : 'SEEED Studios'})
    td.append({'category' : 'size', 'code' : 'SPAR', 'name' : 'Sparkfun'})
    td.append({'category' : 'size', 'code' : 'PANB', 'name' : 'SMD (4 mm) (Panasonic B)'})
    td.append({'category' : 'size', 'code' : 'PANC', 'name' : 'SMD (5 mm) (Panasonic C)'})
    td.append({'category' : 'size', 'code' : 'PAND', 'name' : 'SMD (6.3 mm) (Panasonic D)'})
    td.append({'category' : 'size', 'code' : 'PAND8', 'name' : 'SMD (6.3 mm) (Panasonic D8)'})
    td.append({'category' : 'size', 'code' : 'PANE', 'name' : 'SMD (8 mm) (Panasonic E)'})
    td.append({'category' : 'size', 'code' : 'PANF', 'name' : 'SMD (8 mm) (Panasonic F)'})
    td.append({'category' : 'size', 'code' : 'PANG', 'name' : 'SMD (10 mm) (Panasonic G)'})
    td.append({'category' : 'size', 'code' : 'ELLA', 'name' : 'Electro Lama'})
