

def load(td):
    td.append({'category' : 'type', 'code' : 'ANTE', 'name' : 'Antenna'})
    td.append({'category' : 'type', 'code' : 'BAHO', 'name' : 'Battery Holder'})
    td.append({'category' : 'type', 'code' : 'BAPI', 'name' : 'Badge Pin'})
    td.append({'category' : 'type', 'code' : 'BREB', 'name' : 'Breadboard'})
    td.append({'category' : 'type', 'code' : 'BUTA', 'name' : 'Pushbutton (Tactile)'})
    td.append({'category' : 'type', 'code' : 'BUTP', 'name' : 'Pushbutton'})
    td.append({'category' : 'type', 'code' : 'BUZZ', 'name' : 'Buzzer'})
    td.append({'category' : 'type', 'code' : 'CABL', 'name' : 'Cable'})
    td.append({'category' : 'type', 'code' : 'CAPC', 'name' : 'Capacitor (Ceramic)'})
    td.append({'category' : 'type', 'code' : 'CAPE', 'name' : 'Capacitor (Electrolytic)'})
    td.append({'category' : 'type', 'code' : 'CAPT', 'name' : 'Capacitor (Tantalum)'})
    td.append({'category' : 'type', 'code' : 'CERE', 'name' : 'Ceramic Resonator'})
    td.append({'category' : 'type', 'code' : 'DBCO', 'name' : 'Connector'})
    td.append({'category' : 'type', 'code' : 'CRHO', 'name' : 'Crimp Housing'})
    td.append({'category' : 'type', 'code' : 'DCJP', 'name' : 'DC Jack'})
    td.append({'category' : 'type', 'code' : 'DCPP', 'name' : 'DC Plug'})
    td.append({'category' : 'type', 'code' : 'DIOD', 'name' : 'Diode'})
    td.append({'category' : 'type', 'code' : 'DIOS', 'name' : 'Diode (Schottky)'})
    td.append({'category' : 'type', 'code' : 'DISP', 'name' : 'Display'})
    td.append({'category' : 'type', 'code' : 'FERB', 'name' : 'Ferrite Bead'})
    td.append({'category' : 'type', 'code' : 'HEAD', 'name' : 'Header'})
    td.append({'category' : 'type', 'code' : 'HEAS', 'name' : 'Header (Socket)'})
    td.append({'category' : 'type', 'code' : 'HEAL', 'name' : 'Header (Long)'})
    td.append({'category' : 'type', 'code' : 'HEDS', 'name' : 'Headphone Socket'})
    td.append({'category' : 'type', 'code' : 'HELF', 'name' : 'Female Header (Long)'})
    td.append({'category' : 'type', 'code' : 'HESH', 'name' : 'Heat Shrink'})
    td.append({'category' : 'type', 'code' : 'ICIC', 'name' : ''})
    td.append({'category' : 'type', 'code' : 'MCUU', 'name' : 'MCU'})
    td.append({'category' : 'type', 'code' : 'ICSO', 'name' : 'IC Socket'})
    td.append({'category' : 'type', 'code' : 'INDU', 'name' : 'Inductor'})
    td.append({'category' : 'type', 'code' : 'JSTS', 'name' : 'JST Socket'})
    td.append({'category' : 'type', 'code' : 'JUMP', 'name' : 'Jumper'})
    td.append({'category' : 'type', 'code' : 'LEDS', 'name' : 'LED'})
    td.append({'category' : 'type', 'code' : 'MICR', 'name' : 'Microphone'})
    td.append({'category' : 'type', 'code' : 'MOSN', 'name' : 'N-Ch. MOSFET'})
    td.append({'category' : 'type', 'code' : 'MOSP', 'name' : 'P-Ch. MOSFET'})
    td.append({'category' : 'type', 'code' : 'MOTO', 'name' : 'Motor'})
    td.append({'category' : 'type', 'code' : 'MOTV', 'name' : 'Motor (Vibrating)'})
    td.append({'category' : 'type', 'code' : 'NHFF', 'name' : 'Nylon Standoff (F-F)'})
    td.append({'category' : 'type', 'code' : 'NNUT', 'name' : 'Nylon Nut'})
    td.append({'category' : 'type', 'code' : 'NSCR', 'name' : 'Nylon Screw'})
    td.append({'category' : 'type', 'code' : 'NUTT', 'name' : 'Nut'})
    td.append({'category' : 'type', 'code' : 'OPAM', 'name' : 'Op Amp'})
    td.append({'category' : 'type', 'code' : 'PHTR', 'name' : 'Phototransistor'})
    td.append({'category' : 'type', 'code' : 'POTE', 'name' : 'Potentiometer'})
    td.append({'category' : 'type', 'code' : 'PIEZ', 'name' : 'Piezo Element'})
    td.append({'category' : 'type', 'code' : 'POAD', 'name' : 'Power Adapter'})
    td.append({'category' : 'type', 'code' : 'PRIV', 'name' : 'Plastic Rivet'})
    td.append({'category' : 'type', 'code' : 'RBCC', 'name' : 'Crimped Ribbon Cable'})
    td.append({'category' : 'type', 'code' : 'REFU', 'name' : 'Resetable Fuse'})
    td.append({'category' : 'type', 'code' : 'RELA', 'name' : 'Relay'})
    td.append({'category' : 'type', 'code' : 'RESA', 'name' : 'Resistor Array'})
    td.append({'category' : 'type', 'code' : 'RESE', 'name' : 'Resistor'})
    td.append({'category' : 'type', 'code' : 'RJ45', 'name' : 'RJ45'})
    td.append({'category' : 'type', 'code' : 'SCRE', 'name' : 'Machine Screw'})
    td.append({'category' : 'type', 'code' : 'SDCS', 'name' : 'SD Card Socket'})
    td.append({'category' : 'type', 'code' : 'SENS', 'name' : 'Sensor'})
    td.append({'category' : 'type', 'code' : 'SERV', 'name' : 'Servo'})
    td.append({'category' : 'type', 'code' : 'SWIS', 'name' : 'Switch (Slide)'})
    td.append({'category' : 'type', 'code' : 'TERS', 'name' : 'Screw Terminal'})
    td.append({'category' : 'type', 'code' : 'THER', 'name' : 'Thermistor'})
    td.append({'category' : 'type', 'code' : 'TILS', 'name' : 'Tilt Switch'})
    td.append({'category' : 'type', 'code' : 'TINB', 'name' : 'Tin Box'})
    td.append({'category' : 'type', 'code' : 'TRNN', 'name' : 'NPN Transistor'})
    td.append({'category' : 'type', 'code' : 'TRNP', 'name' : 'PNP Transistor'})
    td.append({'category' : 'type', 'code' : 'USBS', 'name' : 'USB Socket'})
    td.append({'category' : 'type', 'code' : 'UFLS', 'name' : 'UFL Socket'})
    td.append({'category' : 'type', 'code' : 'VARI', 'name' : 'Varistor'})
    td.append({'category' : 'type', 'code' : 'VREG', 'name' : 'Voltage Regulator'})
    td.append({'category' : 'type', 'code' : 'WIRS', 'name' : 'Stranded Wire'})
    td.append({'category' : 'type', 'code' : 'XTAL', 'name' : 'Crystal'})
